---
- name: add splunk indexing tier to local hosts file
  lineinfile: /etc/hosts
    regexp="^"
    insertafter="^"
    line="0.0.0.0 splunk"
    state=present

- name: copy over the splunk installation deb
  copy: src={{ splunk_filename }} dest=/tmp

- name: install splunk with dpkg
  command: dpkg -i /tmp/{{ splunk_filename }} creates=/opt/splunkforwarder

- name: splunk license
  command: /opt/splunkforwarder/bin/splunk start --answer-yes --no-prompt --accept-license creates=/opt/splunkforwarder/etc/users/splunk-system-user
  
  -name: log into splunk
  command: /opt/splunk/bin/splunk login -auth admin:changeme
  
  -name: change splunk password
  command /opt/splunk/bin/splunk edit user admin password bRe6w!_utRUVeC7h

- name: setup to start at boot
  command: /opt/splunkforwarder/bin/splunk enable boot-start

- name: connect to splunk server
  command: /opt/splunkforwarder/bin/splunk add forward-server splunk:9997 -auth admin:bRe6w!_utRUVeC7h
